# Generated by Django 4.1.7 on 2023-03-20 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KISILER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TAKI_TURU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GELEN_TAKILAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AD', models.TextField(db_column='Ad')),
                ('SOYAD', models.TextField(blank=True, db_column='Soyad', null=True)),
                ('ACIKLAMA', models.TextField(blank=True, null=True)),
                ('MIKTAR', models.IntegerField(blank=True, null=True)),
                ('KISI', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sunnet.kisiler')),
                ('TAKI_TUR', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sunnet.taki_turu')),
            ],
        ),
    ]
