# Generated by Django 4.1.7 on 2023-03-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunnet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kisiler',
            old_name='ad',
            new_name='AD',
        ),
        migrations.RenameField(
            model_name='taki_turu',
            old_name='ismi',
            new_name='AD',
        ),
    ]
