# Generated by Django 4.1.7 on 2023-03-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunnet', '0002_rename_ad_kisiler_ad_rename_ismi_taki_turu_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisiler',
            name='AD',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
