# Generated by Django 4.1.7 on 2023-03-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunnet', '0003_alter_kisiler_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisiler',
            name='AD',
            field=models.TextField(blank=True, null=True),
        ),
    ]
